const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

async function main() {
    const provider = new ethers.JsonRpcProvider(process.env.ALCHEMY_SEPOLIA_URL);
    const wallet = new ethers.Wallet(process.env.DEPLOYER_PRIVATE_KEY, provider);

    console.log("Deploying with:", wallet.address);
    const balance = await provider.getBalance(wallet.address);
    console.log("Balance:", ethers.formatEther(balance), "ETH");

    if (balance === 0n) {
        console.error("❌ Error: Wallet has no ETH. Please get some Sepolia ETH first.");
        process.exit(1);
    }

    const usdcAddress = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238";
    console.log("\n[1/2] Using Circle Sepolia USDC:", usdcAddress);

    // Load ABIs and Bytecode
    const factoryArtifact = JSON.parse(fs.readFileSync(path.join(__dirname, "../artifacts/contracts/MarketFactory.sol/MarketFactory.json"), "utf8"));
    const marketArtifact = JSON.parse(fs.readFileSync(path.join(__dirname, "../artifacts/contracts/PredictionMarket.sol/PredictionMarket.json"), "utf8"));

    // Deploy Factory
    console.log("\n[2/2] Deploying MarketFactory...");
    const Factory = new ethers.ContractFactory(factoryArtifact.abi, factoryArtifact.bytecode, wallet);
    const factory = await Factory.deploy(usdcAddress);
    await factory.waitForDeployment();
    const factoryAddress = await factory.getAddress();
    console.log("✅ MarketFactory deployed:", factoryAddress);

    // Create Initial Market
    console.log("\n[3] Creating initial market...");
    const resolutionTime = Math.floor(Date.now() / 1000) + 30 * 24 * 3600; // 30 days
    const tx = await factory.createMarket(
        "Ethereum to reach $4,000 by June 2026?",
        "Crypto",
        resolutionTime
    );
    await tx.wait();
    console.log("✅ Initial market created on Sepolia");

    // Update contracts.js
    const contractsPath = path.join(__dirname, "../src/lib/contracts.js");
    const contractsContent = `// AUTO-GENERATED by deploy_simple.js — DO NOT EDIT MANUALLY
export const CONTRACT_ADDRESSES = {
  USDC: "${usdcAddress}",
  MARKET_FACTORY: "${factoryAddress}",
};

export const NETWORK = {
  chainId: 11155111,
  name: "Ethereum Sepolia",
};

export const IS_DEPLOYED = true;
`;
    fs.writeFileSync(contractsPath, contractsContent);
    console.log("\n✅ contracts.js updated");

    console.log("\n═══════════════════════════════════════════");
    console.log("DEPLOYMENT COMPLETE");
    console.log("═══════════════════════════════════════════");
    console.log("Factory:", factoryAddress);
}

main().catch(console.error);
