const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  // ─── 1. Use Official Sepolia USDC ─────────────────────────────────────────
  const usdcAddress = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238";
  console.log("\n[1/2] Using Circle Sepolia USDC:", usdcAddress);

  // ─── 2. Deploy MarketFactory ──────────────────────────────────────────────
  console.log("\n[2/2] Deploying MarketFactory...");
  const MarketFactory = await ethers.getContractFactory("MarketFactory");
  const factory = await MarketFactory.deploy(usdcAddress);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log("✅ MarketFactory deployed:", factoryAddress);

  // ─── 3. Create initial demo market ───────────────────────────────────────
  console.log("\n[3] Creating initial market...");
  const resolutionTime = Math.floor(Date.now() / 1000) + 30 * 24 * 3600; // 30 days
  const tx = await factory.createMarket(
    "Ethereum to reach $4,000 by June 2026?",
    "Crypto",
    resolutionTime
  );
  await tx.wait();
  console.log("✅ Initial market created on Sepolia");

  // ─── Update contracts.js in frontend ─────────────────────────────────────
  const contractsPath = path.join(__dirname, "../src/lib/contracts.js");
  const contractsContent = `// AUTO-GENERATED by deploy.js — DO NOT EDIT MANUALLY
// Network: Ethereum Sepolia
// Deployed: ${new Date().toISOString()}

export const CONTRACT_ADDRESSES = {
  USDC: "${usdcAddress}",
  MARKET_FACTORY: "${factoryAddress}",
};

export const NETWORK = {
  chainId: 11155111,
  name: "Ethereum Sepolia",
  rpcUrl: process.env.VITE_ALCHEMY_SEPOLIA_URL || "https://rpc.sepolia.org",
};
`;
  fs.writeFileSync(contractsPath, contractsContent);
  console.log("\n✅ contracts.js updated at:", contractsPath);

  console.log("\n═══════════════════════════════════════════");
  console.log("REAL SEPOLIA DEPLOYMENT COMPLETE");
  console.log("═══════════════════════════════════════════");
  console.log("USDC Address: ", usdcAddress);
  console.log("MarketFactory:", factoryAddress);
  console.log("\nVerify on Etherscan:");
  console.log(`npx hardhat verify --network sepolia ${usdcAddress}`);
  console.log(`npx hardhat verify --network sepolia ${factoryAddress} "${usdcAddress}"`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
